name: Php Codesniffer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
      
permissions:
  contents: read
  
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # important!
          
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run phpcs
        run: ./vendor/bin/phpcs -s -p --colors src/Doodle/ 

      - name: Run phpcbf
        run: ./vendor/bin/phpcbf -s -p --colors src/Doodle/